server:
  port: 8080

spring:
  application:
    name: jari-gateway
  springdoc:
    swagger-ui:
      urls:
        - name: Auth Service
          url: /auth-service/v3/api-docs
        - name: User Service
          url: /user-service/v3/api-docs
        - name: Project Service
          url: /project-service/v3/api-docs
        - name: Task Service
          url: /task-service/v3/api-docs
        - name: Notification Service
          url: /notification-service/v3/api-docs
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://jari-auth-service
          predicates:
            - Path=/auth/**
          # No AuthenticationFilter for auth routes
        - id: user-service
          uri: lb://jari-user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: project-service
          uri: lb://jari-project-service
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: task-service
          uri: lb://jari-task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: notification-service
          uri: lb://jari-notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        # Swagger Documentation Routes
        - id: user-service-v3-docs
          uri: lb://jari-user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/(?<path>.*), /${path}
        - id: project-service-v3-docs
          uri: lb://jari-project-service
          predicates:
            - Path=/project-service/v3/api-docs
          filters:
            - RewritePath=/project-service/(?<path>.*), /${path}
        - id: task-service-v3-docs
          uri: lb://jari-task-service
          predicates:
            - Path=/task-service/v3/api-docs
          filters:
            - RewritePath=/task-service/(?<path>.*), /${path}
        - id: notification-service-v3-docs
          uri: lb://jari-notification-service
          predicates:
            - Path=/notification-service/v3/api-docs
          filters:
            - RewritePath=/notification-service/(?<path>.*), /${path}
        - id: auth-service-v3-docs
          uri: lb://jari-auth-service
          predicates:
            - Path=/auth-service/v3/api-docs
          filters:
            - RewritePath=/auth-service/(?<path>.*), /${path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
