server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: jari-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://jari-auth-service
          predicates:
            - Path=/auth/**
          # No AuthenticationFilter for auth routes
        - id: user-service
          uri: lb://jari-user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: project-service
          uri: lb://jari-project-service
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: task-service
          uri: lb://jari-task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: notification-service
          uri: lb://jari-notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        # Swagger Documentation Routes
        - id: user-service-v3-docs
          uri: lb://jari-user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs
        - id: project-service-v3-docs
          uri: lb://jari-project-service
          predicates:
            - Path=/v3/api-docs/project-service
          filters:
            - RewritePath=/v3/api-docs/project-service, /v3/api-docs
        - id: task-service-v3-docs
          uri: lb://jari-task-service
          predicates:
            - Path=/v3/api-docs/task-service
          filters:
            - RewritePath=/v3/api-docs/task-service, /v3/api-docs
        - id: notification-service-v3-docs
          uri: lb://jari-notification-service
          predicates:
            - Path=/v3/api-docs/notification-service
          filters:
            - RewritePath=/v3/api-docs/notification-service, /v3/api-docs
        - id: auth-service-v3-docs
          uri: lb://jari-auth-service
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - RewritePath=/v3/api-docs/auth-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth-service
      - name: User Service
        url: /v3/api-docs/user-service
      - name: Project Service
        url: /v3/api-docs/project-service
      - name: Task Service
        url: /v3/api-docs/task-service
      - name: Notification Service
        url: /v3/api-docs/notification-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
